version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: whatsapp-agent-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=whatsapp-agent
    networks:
      - whatsapp-agent-network
    restart: unless-stopped

networks:
  whatsapp-agent-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 